# .streamlit/config.toml
[theme]
base = "light"
primaryColor = "#1E40AF"          # Azul corporativo
backgroundColor = "#F8FAFC"       # Blanco de fondo principal
secondaryBackgroundColor = "#F1F5F9" # Gris claro limpio para Sidebar y submenús
textColor = "#0F172A"             # Azul oscuro/Negro para que todo el texto contraste
